#!/usr/bin/env bash
# Configure ufw firewall rules

sudo apt-get update
sudo apt-get ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo service ufw enable
