#!/usr/bin/env bash
# Configures Nginx to add a custom header X-Served-By with the server's hostname
# shellcheck disable=SC2154

# Update packages and install Nginx
apt-get update -y
apt-get install -y nginx

# Add custom header configuration inside the Nginx default site config right below server_name _;
sed -i "s|server_name _;|server_name _;\n\tadd_header X-Served-By \$hostname;|" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
