#!/usr/bin/env bash
# Configures Nginx to add a custom HTTP response header X-Served-By

apt-get update
apt-get install -y nginx

# Add X-Served-By header with the hostname inside the Nginx default site config
sed -i "/server_name _;/a \\\tadd_header X-Served-By \$HOSTNAME;" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
