#!/usr/bin/env bash
# Configures Nginx to include a custom HTTP header X-Served-By containing the server hostname

sudo apt-get update
sudo apt-get -y install nginx

sudo sed -i "/http {/a \\\tadd_header X-Served-By \$HOSTNAME;" /etc/nginx/nginx.conf

sudo nginx -t && sudo service nginx restart
