#!/usr/bin/env bash
# Configures a new Ubuntu machine with Nginx returning "Holberton School"

apt-get update -y
apt-get install -y nginx

# Configure the default index file with the required string
echo "Holberton School for the win!" > /var/www/html/index.html

# Start Nginx service without systemctl
service nginx start
