#!/usr/bin/env bash
# Configures Nginx
apt-get update -y
apt-get install -y nginx
mkdir -p /var/www/html /usr/share/nginx/html
echo "Holberton School for the win!" > /var/www/html/index.html
echo "Holberton School for the win!" > /usr/share/nginx/html/index.html
service nginx restart
