#!/usr/bin/env bash
# Configures a new Ubuntu machine with Nginx returning "Holberton School"

sudo apt-get update -y
sudo apt-get install -y nginx

# Configure the default index file with the required string
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html

# Start Nginx service without systemctl
sudo service nginx start || sudo service nginx restart
